### ISSUE TITLE
[Feature] Strip Types (maybe JSX)

### ISSUE THREAD

**Issue by verydanny** [escaya/escaya-codegen#8]
I realize adding TypeScript support is tough because of lookaheads (according to a comment you made somewhere), but how hard would it be to implement type stripping or JSX support? I need a quick parser + code generator for an ES module plugin I'm writing, but I currently have to transform the code with 2 parsers. Funny enough, using 2 parsers + **astring** (as the generator) is still 5x faster than using Babel even once.

Also, what how many parsers are you working on? I know you contribute to **meriyah**, but what is **seafox** and the other parsers you wrote? Where did **buntis** go?

**P.S:** I love this parser and the idea that we don't have to be shackled to Babel and other slow parsers. I'd like to contribute if possible (financially) because lord knows you're a much better dev than I am (jealous of those skills).

**Edit:** Meant to post this in the **escaya** parser, sorry.

**Comment by KFlash** [comment]
Hi. You are right. Adding TS support to Escaya is super hard because of the fact that TS loves lookahead. JSX isn't that hard and should be possible. Stripping of types I'm not sure about that because it would require that the parser actually handle the types somehow.

I'm aware Babel is super slow, but that isn't huge surprise :)  

Meriyah was made by my students, and seafox was an experiment I did based on that. Buntis was a student work as well.

So after what I understand is that you need a TypeScript parser that support JSX and strip types and generate a printed output?

That's a goal I have hard to achieve with Escaya, but I will invite you to a private repo of mine. I think that should solve what you want :)

Everything is possible so if you want to contribute, it's okay. Just open an issue about in the repo I sent you an invite too and we can talk about it there.

**Comment by verydanny** [comment]
That sounds fun. I'm really just looking to learn more about ASTs, optimizations, etc. Say I transformed code to AST successfully, what's the best way to traverse it? Here's what I'm really looking to do:

```js
```

**Comment by KFlash** [comment]
Do you need to parse the source for that? Seems like an overkill.

Try click [on this link](https://github.com/kataw/kataw)

**Comment by verydanny** [comment]
Well, it would help to know the difference between `ImportCall`, `ImportDecleration`, and require. Would you suggest a match/replace or something else? I want to "stub" those modules and then output valid ECMAScript. I feel like if I did match or replace then I would get fringe cases of it failing--although it would probably be magnitudes faster.

**Comment by KFlash** [comment]
Go to the repo I linked too, and we can discuss it further there. I created an TODO so you know what I'm going to do.

**Comment by KFlash** [comment]
@verydanny friendly ping

**Comment by verydanny** [comment]
@verydanny thanks! I will go and explore. I've been a bit busy lately.

**Comment by KFlash** [comment]
@verydanny This is what you are looking for right? And want to archieve?

![badhehe](https://user-images.githubusercontent.com/31855118/103715263-1ef9b900-4ffb-11eb-92aa-b7f115b21cb1.png)

**Comment by KFlash** [comment]
@verydanny I did some research, and you can't just "strip off" TS types unless you write 100% syntax correct JS. You will need an transformer that transform from TS to JS as in Babel, and probably also an linter.

I can pinpoint one example - TS access modifiers in formal parameters.  They are valid in JS sloppy mode, but will "disappear" if you "strip them off", and you also will sit back with a "," expected issue ;)

This is what will happen. [Click on this link](https://kataw.github.io/kataw/kataw_print/?code=function%20x(public%20protected%20private)%20%20%7B%7D&method=parse&range=undefined&loc=false&next=false&cst=false&module=false&raw=undefined&jsx=undefined&directives=undefined&attachComment=undefined&webCompat=undefined&lexical=undefined)

So "strip off" are nearly impossible. I'm working on transformers now privately , and it's always a question about time, money and priority.

But JSX can and will be added to Escaya in the future. TS isn't possible in Escaya.
